language: node_js
node_js:
  - "8.2.1"
  - "10"

before_script:
  - npm run start &

script:
  - npm run build:prod

after_success:
  - test $TRAVIS_BRANCH = "source" && test $TRAVIS_PULL_REQUEST = "false" && npm run deploy

notifications:
  - email:
    on_failure: change
    on_success: change
